general:
  version: 1
  title_delay: 8000
  default_world: pools

populators:

  pools_exit:
    type: waterfall
    next_level: dark_pools
    command_blocks: true
    exit_level: -32

  dark_pools_loot:
    type: loot
    drops:
      shears:
        block: barrel
        weight: 0.2
        items:
          - kelp_shears
      diving_helmet:
        block: barrel
        weight: 0.1
        items:
          - diving_helmet
      coal:
        block: barrel
        weight: 0.1
        items:
          - coal
      smoker:
        block: smoker
        weight: 1
        items:
          - air
          - coal

  dark_pools_vault_loot:
    type: loot
    x: 8
    z: 8
    y: 2
    drops:
      shears:
        block: warped_shelf
        items:
          - kelp_shears
          - diving_helmet

  dark_pools_vault_smoker:
    type: loot
    x: 8
    z: 8
    y: 1
    drops:
      smoker:
        block: smoker
        weight: 1
        items:
          - air
          - coal

  dark_pools_exit:
    type: waterfall
    next_level: ocean
    command_blocks: true
    exit_level: -32

rooms:

  pools:
    type: pools
    bedrock_level: 60
    floor_level: 62
    roof_min_height: 6
    roof_max_height: 16
    doorway_min_height: 3
    doorway_max_height: 6
    doorway_max_width_half: 3
    walkway_max_width_half: 5
    wall_probability: 0.75
    window_probability: 0.3
    island_probability: 0.75
    pool_probability: 0.75
    double_door_probability: 0.5
    food_probability: 0.02
    food_block: minecraft:cave_vines[age=0,berries=true]
    floor_blocks:
      - blue_concrete
      - light_blue_concrete
    wall_blacks:
      - polished_diorite
      - diorite
      - quartz_block
    ceiling_blacks:
      - polished_diorite
      - diorite
      - quartz_block
    light_blocks:
      - sea_lantern

  pools_exit:
    min_distance: 640
    max_distance: 3200
    weight: 0.1
    inherit: pools
    populators:
      - pools_exit

  dark_pools:
    type: pools
    food_location: 7
    bedrock_level: 18
    sunroof_probability: 0.25
    hallway_min_width_half: 0
    hallway_max_width_half: 3
    floor_level: 22
    roof_min_height: 3
    roof_max_height: 6
    doorway_min_height: 2
    doorway_max_height: 4
    doorway_max_width_half: 3
    walkway_max_width_half: 3
    light_probability: 0.1
    wall_probability: 0.8
    window_probability: 0.1
    island_probability: 0.75
    pool_probability: 0.75
    double_door_probability: 0.1
    food_probability: 0.1
    underwater_food_probability: 0.2
    food_type: underwater
    food_block: minecraft:kelp_plant
    flooding_probability: 0.5
    flooding_min_level: 1
    flooding_max_level: 4
    water_depth_max: 3
    floor_blocks:
      - blue_concrete
      - light_blue_concrete
    wall_blacks:
      - polished_diorite
      - diorite
      - quartz_block
    ceiling_blacks:
      - polished_diorite
      - diorite
      - quartz_block
    light_blocks:
      - sea_lantern

  dark_pools_exit:
    inherit: dark_pools
    min_distance: 640
    max_distance: 3200
    weight: 0.2
    populators:
      - dark_pools_exit

  dark_pools_loot:
    inherit: dark_pools
    min_distance: 256
    max_distance: 1024
    weight: 0.05
    populators:
      - dark_pools_loot

  dark_pools_vault:
    inherit: dark_pools
    min_distance: 32
    max_distance: 1024
    weight: 0.1
    hallway_min_width_half: 6
    hallway_max_width_half: 6
    doorway_max_width_half: 6
    doorway_min_width_half: 6
    sunroof_probability: 0.75
    doorway_min_height: 4
    doorway_max_height: 4
    roof_min_height: 4
    roof_max_height: 6
    light_probability: 1
    floor_light_probability: 1
    wall_probability: 1
    window_probability: 0
    island_probability: 1
    pool_probability: 0
    double_door_probability: 1
    food_probability: 0
    flooding_probability: 0
    populators:
      - dark_pools_vault_loot
      - dark_pools_vault_smoker
    floor_blocks:
      - quartz_block
    wall_blocks:
      - iron_block
    ceiling_blacks:
      - iron_block
    light_blocks:
      - glowstone

  ocean:
    type: ocean
    sea_level: 190
    sand_level: 6
    bedrock_level: 1

worlds:

  pools:
    title_delay: 2000
    title: "&bThe Shallow Pools"
    time: 6000
    biome: lush_caves
    rooms:
      - pools
      - pools_exit

  dark_pools:
    title: "&3The Dark Pools"
    time: 18000
    rain: true
    biome: lush_caves
    rooms:
      - dark_pools
      - dark_pools_exit
      - dark_pools_loot
      - dark_pools_vault

  ocean:
    title: "&8The Abyss"
    biome: deep_ocean
    time: 18000
    rooms:
      - ocean

items:
  diving_helmet:
    name: "&bDiving Helmet"
    item: chainmail_helmet[attribute_modifiers=[{id:"oxygen",type:"oxygen_bonus",amount:1000000,operation:"add_value",slot:"head",display:{type:"hidden"}}],tooltip_display={hidden_components:["attribute_modifiers"]}]
    lore:
      - Wear to breathe underwater
  kelp_shears:
    name: "&bKelp Shears"
    item: shears[minecraft:can_break={blocks:["minecraft:kelp_plant","minecraft:kelp"]}]
