name: LiminalDeep
main: com.elmakers.mine.bukkit.plugins.liminal.LiminalWorldPlugin
version: ${project.version}
api-version: 26.1
website: http://mine.elmakers.com
author: NathanWolf,TheCrystalOfTheArchitect
description: A pool-based liminal horror Bukkit mod for Minecraft. Find out what lurks beneath...
load: STARTUP
commands:
  liminal:
    permission: liminal
    description: Commands for the liminal plugin
    usage: |
      /liminal go <pools|ocean>        Go to a specific liminal area
      /liminal give <player> <item>    Give a liminal item to a player
      /liminal reload                  Reload some configs
